### ISSUE TITLE
Question: EC2 Container Service vs Elastic Beanstalk and ION-Roller

### ISSUE THREAD

**Issue by ambrons** [gilt/ionroller#16]
I've been looking over the repository as well as reading over this article:
http://www.infoq.com/articles/gilt-deploying-microservices-aws

My team is in the process of evaluating our devops options with AWS.  We've looked at both Elastic Beanstalk and EC2 Container Service.  We're leaning more towards EC2 Container Service over Elastic Beanstalk, primarily looking at the features available with `ecs-cli`, `compose`, and the ease to bring up clusters of instances for the needs at hand.

In the process we ran across this repo and noticed it's built on top of EC2 / Elastic Beanstalk.  Has anyone evaluated if ECS (EC2 Container Service) has the same limitation as Elastic Beanstalk, EC2, and CodeDeploy that was identified during the conception of ION-Roller?

For reference he's an example of what's possible with `ecs-cli`:
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html

Also a talk from the Docker guys showing similar functionality.
https://www.youtube.com/watch?v=7CZFpHUPqXw

**Comment by fiadliel** [comment]
At the point when ionroller was initially written, ECS was not available. Then, after it became available, it had significant limitations, including (but not exclusively) the lack of integration with ELBs, the inability to change the number of instances in a task after creation, and the lack of control over the lifecycle (what happens after your Docker image finishes running).

These limitations have been gradually removed by AWS over time, but it's not quite there yet. I think both lifecycle management, and #instance changes have been added. ELB integration has been added too, with some missing abilities, e.g. http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html - the ELB requires that every instance run on the same port, limiting you to one instance per IP address. This may be suboptimal, if you hope to be able to pack more than one instance of a task on the same machine.

One consequence of requiring a specific port is that it's hard to do blue/green deployments; the port you would like to use is already in use by the previously running environment.

**Comment by ambrons** [comment]
Thanks for the information.  I spend a few days looking over the land scape again and appears AWS ECS just isn't there, YET as you stated.

This ticket can be closed, thanks.

**Comment by velmu** [comment]
Fiadliel, its a good point out. "limiting you to one instance per IP address" ?, is this statement mean, we can use only one IP address per Instance?

**Comment by fiadliel** [comment]
As of now, the Amazon ELB has a single defined port in its configuration, and the list of defined targets does not include a custom port. As a result, all running instances of a service should be running on that exact port.

My comment on IP addresses is that because ports are namespaced by IP address; if you could get more IP addresses, you could run more instances on the same port.

**Comment by tsillan** [comment]
It seems the Application Load Balancer announced in August 2016 may address the above mentioned port issues, if I understood the problem correctly. ALB allows multiple tasks from a single service on the same instance due to dynamic host port mapping:
[http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html](url)
