### ISSUE TITLE
Question: Docker Configuration and Number of EC2 Containers

### ISSUE THREAD

**Issue by ambrons** [gilt/ionroller#18]
This question is related to the philosophy of ION Roller and microservices.  We've been using ION Roller locally for a greenfield application we're building.  Each service is its own application in EB deployed and managed by ION Roller.

I come from OpenStack and OneOps (recently opensourced tool by Walmart Labs).  So I wasn't expecting to run into resource limits in AWS with this architecture.  However it appears you can only have 20 on-demand EC2 instances in your account per region, without requesting more resources.  I'll be up front and I haven't made the request yet, but it feels like an extremely small number when you start talking about docker and microservices.

I've read that Guilt uses 75+ microservices.  Could you elaborate a little on a few points:
1. Do you use single docker containers or multidocker containers?  I know that EB / ECS supports both.  Not entirely sure that ION Roller works with both.
2. Did you request more EC2 instances for your account?  What it difficult to get approved?

**Comment by fiadliel** [comment]
1. We use single Docker containers (usually you would use multiple containers grouped together to manage accompanying daemons like logging tools etc.)

2. Yes, we have requested more instances for accounts. See http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html for details, the process is fairly painless.

Note that we actually use a number tools for deploying images (not just this one). But the questions are valid for any Docker deployment system using AWS (especially one using one service per VM/instance rather than sharing resources like ECS does).
